[supervisord]
nodaemon=true

[program:php-fpm]
command=php-fpm
priority=10
autostart=true
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
priority=20
autostart=true
autorestart=true

[program:queue]
command=php /var/www/html/artisan queue:work redis --queue=analysis,rendering,default --timeout=3600 --tries=3
priority=30
autostart=true
autorestart=true
stdout_logfile=/var/www/html/storage/logs/queue-worker.log
stderr_logfile=/var/www/html/storage/logs/queue-worker-error.log
