<?php

return [
    'max_upload_mb' => (int) env('VIDEO_MAX_UPLOAD_MB', 1024),
    'media_disk' => env('MEDIA_DISK', 'local'),
    'ffmpeg_path' => env('FFMPEG_BIN', '/usr/bin/ffmpeg'),
    'ffprobe_path' => env('FFPROBE_BIN', '/usr/bin/ffprobe'),
    'youtube_ingestion_enabled' => (bool) env('YOUTUBE_INGESTION_ENABLED', false),
    'ytdlp_path' => env('YTDLP_BIN', '/usr/local/bin/yt-dlp'),
    'render_timeout' => (int) env('RENDER_TIMEOUT', 3600),
    'normalize_on_upload' => (bool) env('NORMALIZE_ON_UPLOAD', true),
    'normalize_timeout' => (int) env('NORMALIZE_TIMEOUT', 3600),
    'normalize_preset' => env('NORMALIZE_PRESET', 'veryfast'),
    'normalize_crf' => (int) env('NORMALIZE_CRF', 20),
    'normalized_prefix' => env('NORMALIZED_PREFIX', 'projects'),
    'render_preset' => env('RENDER_PRESET', 'veryfast'),
    'render_crf' => (int) env('RENDER_CRF', 23),
    'analysis_timeout' => (int) env('ANALYSIS_TIMEOUT', 1800),
    'signal_timeout' => (int) env('SIGNAL_TIMEOUT', 300),
    'silence_noise' => env('SILENCE_NOISE', '-35dB'),
    'silence_duration' => env('SILENCE_DURATION', '0.45'),
    'min_clip_seconds' => (int) env('MIN_CLIP_SECONDS', 18),
    'max_clip_seconds' => (int) env('MAX_CLIP_SECONDS', 75),
    'max_candidate_clips' => (int) env('MAX_CANDIDATE_CLIPS', 5),
    'transcription_language' => env('TRANSCRIPTION_LANGUAGE', 'id'),
    'analysis_queue' => env('ANALYSIS_QUEUE', 'analysis'),
    'render_queue' => env('RENDER_QUEUE', 'rendering'),
    'ai' => ['provider' => env('AI_PROVIDER', 'real')],
    'openai' => [
        'api_key' => env('OPENAI_API_KEY'),
        'transcription_model' => env('OPENAI_TRANSCRIPTION_MODEL', 'whisper-1'),
        'text_model' => env('OPENAI_TEXT_MODEL', null),
        'max_analysis_chars' => (int) env('OPENAI_MAX_ANALYSIS_CHARS', 16000),
        'timeout' => (int) env('OPENAI_TIMEOUT', 900),
    ],
    'whisper' => [
        'bin' => env('WHISPER_BIN'),
        'model' => env('WHISPER_MODEL', 'base'),
        'language' => env('WHISPER_LANGUAGE', null),
        'fp16' => (bool) env('WHISPER_FP16', false),
    ],
    'trends' => ['provider' => env('TREND_PROVIDER', 'youtube')],
    'subtitle_font_file' => env('SUBTITLE_FONT_FILE', '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'),
    'watermark_text' => env('WATERMARK_TEXT', null),
    'default_crop_mode' => env('DEFAULT_CROP_MODE', 'fit_blur'),
    'default_subtitle_style' => [
        'font' => 'DejaVu Sans',
        'size' => 52,
        'position' => 'bottom_center',
        'color' => '#FFFFFF',
        'highlight_color' => '#E3FD57',
        'outline' => true,
    ],
    'platforms' => [
        'shorts' => ['label' => 'YouTube Shorts', 'max_seconds' => 180, 'ratio' => '9:16'],
        'tiktok' => ['label' => 'TikTok', 'max_seconds' => 600, 'ratio' => '9:16'],
        'reels' => ['label' => 'Instagram Reels', 'max_seconds' => 90, 'ratio' => '9:16'],
    ],
];
